from __future__ import annotations

from pathlib import Path
from typing import Protocol

from wordpycket.domain.entities import WordEntry


class ExampleGenerator(Protocol):
    def generate(self, entry: WordEntry, scope: str = ""): ...

    def generate_isolated(self, entry: WordEntry, scope: str = ""): ...

    def correct_entry(self, entry: WordEntry, scope: str = ""): ...

    def correct_entry_isolated(self, entry: WordEntry, scope: str = ""): ...

    def explain_entry(self, entry: WordEntry, scope: str = "", language: str = ""): ...

    def explain_entry_isolated(self, entry: WordEntry, scope: str = "", language: str = ""): ...

    def generate_many(self, entries: list[WordEntry], scope: str = "", progress=None, control=None): ...

    def correct_many(self, entries: list[WordEntry], scope: str = "", progress=None, control=None): ...

    def uses_user_model(self) -> bool: ...

    def model_status(self): ...

    def ensure_model_available(self): ...

    def device_status(self): ...

    def check_model_runtime(self): ...

    def recommended_process_parallelism(self) -> int: ...

    def recommended_supplement_strategy(self) -> dict: ...

    def isolated_command(self) -> list[str]: ...

    def isolated_environment(self) -> dict[str, str]: ...

    def isolated_payload(self, action: str, entry: WordEntry, scope: str, language: str = "") -> str: ...

    def parse_isolated_result(self, stdout: str, stderr: str, returncode: int) -> dict: ...

    def submit_job(self, method: str, params: dict) -> str: ...

    def job_status(self, job_id: str) -> dict: ...


class CsvImportResult(Protocol):
    entries: list[WordEntry]
    language: str


class PdfImportResult(Protocol):
    language: str
    csv_path: Path
    imported_count: int


class CsvDatasetResult(Protocol):
    language: str
    csv_path: Path
    imported_count: int
